AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Application Load Balancer for ECS Seeker Server with DNS and Target Group configuration.

Resources:
  # Application Load Balancer (ALB)
  NetworkingALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: seeker-alb
      Scheme: internet-facing
      Subnets:
        - !ImportValue PublicSubnet1Id
        - !ImportValue PublicSubnet2Id
      SecurityGroups:
        - !ImportValue ALBSGId
      Type: application
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: true
        - Key: deletion_protection.enabled
          Value: false
      Tags:
        - Key: Name
          Value: seeker-alb

  # Target Group for ECS Service
  SeekerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: seeker-target-group
      TargetType: ip
      Port: 8080
      Protocol: HTTP
      VpcId: !ImportValue ECSVpcID
      HealthCheckPath: '/'
      HealthCheckPort: '8080'
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200'
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5

  # Listener for HTTP (Redirect to HTTPS)
  ALBHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref NetworkingALB
      Port: 80
      Protocol: HTTP

  # Listener for HTTPS
  ALBHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref SeekerTargetGroup
      Certificates:
        - CertificateArn: !ImportValue ALBCertificateArn
      LoadBalancerArn: !Ref NetworkingALB
      Port: 443
      Protocol: HTTPS

  # DNS Record for Seeker Server
  DNSRecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn: NetworkingALB
    Properties:
      HostedZoneId: "{{resolve:ssm:/config/infra/devops/hosted-zone-id}}"
      Name: "{{resolve:ssm:/config/infra/devops/dns-record}}"
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !GetAtt NetworkingALB.DNSName

Outputs:
  NetworkingALBArn:
    Description: ALB's ARN
    Value: !Ref NetworkingALB
    Export:
      Name: seeker-alb-arn

  NetworkingALBDNS:
    Description: ALB's DNS
    Value: !GetAtt NetworkingALB.DNSName
    Export:
      Name: seeker-alb-dns

  SeekerTargetGroupArn:
    Description: ARN of the Target Group
    Value: !Ref SeekerTargetGroup
    Export:
      Name: seeker-target-group-arn
