AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Aurora PostgreSQL with specific security groups and subnets.

Parameters:
  NamePrefix: 
    Default: bg-aws-inf-ipi-cloud-rds-prod
    Type: String
    Description: Used to tag Name all resources with a prefix.

  DBClusterIdentifier:
    Description: Identifier for the Aurora PostgreSQL cluster
    Type: String
    Default: aurora-postgres-cluster

  DBName:
    Description: The name of the database to create
    Type: String
    Default: seekerdb

  MasterUsername:
    Description: Master username for the database
    Type: String
    Default: seeker

  MasterUserPassword:
    Description: Master password for the database
    Type: String
    NoEcho: true

  InstanceClass:
    Description: Instance class for the Aurora instances
    Type: String
    Default: db.r5.large

Resources:
  # Grupo de subredes para Aurora PostgreSQL
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora PostgreSQL
      SubnetIds:
        - !ImportValue RDSSeekerPrivateSubnet1ID
        - !ImportValue RDSSeekerPrivateSubnet2ID
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-aurora-postgres-subnet-group

  # Clúster Aurora PostgreSQL
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DatabaseName: !Ref DBName
      Engine: aurora-postgresql
      EngineVersion: "15.10"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      StorageEncrypted: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue SeekerDBSecurityGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 02:00-03:00
      PreferredMaintenanceWindow: Sun:03:00-Sun:04:00
      Tags:
        - Key: Name
          Value: aurora-postgres-cluster

  # Instancia Aurora PostgreSQL
  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: aurora-postgres-instance
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-postgresql
      DBInstanceClass: !Ref InstanceClass
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-aurora-postgres-instance

Outputs:
  DBClusterIdentifier:
    Description: Identifier of the Aurora PostgreSQL cluster
    Value: !Ref DBClusterIdentifier



------------------------------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Aurora PostgreSQL with specific security groups and subnets.

Parameters:
  NamePrefix: 
    Default: bg-aws-inf-ipi-cloud-rds-prod
    Type: String
    Description: Used to tag Name all resources with a prefix.

  DBClusterIdentifier:
    Description: Identifier for the Aurora PostgreSQL cluster
    Type: String
    Default: aurora-postgres-cluster

  DBName:
    Description: The name of the database to create
    Type: String
    Default: aurora_db

  MasterUsername:
    Description: Master username for the database
    Type: String
    Default: admin

  MasterUserPassword:
    Description: Master password for the database
    Type: String
    NoEcho: true

  InstanceClass:
    Description: Instance class for the Aurora instances
    Type: String
    Default: db.r5.large

Resources:
  AuroraDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for Aurora PostgreSQL with custom settings
      Family: aurora-postgresql13
      Parameters:
        shared_buffers: "120MB"
        work_mem: "100MB"
        max_wal_senders: "0"
      Tags:
        - Key: Name
          Value: aurora-postgres-custom-parameter-group

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora PostgreSQL
      SubnetIds:
        - !ImportValue RDSSeekerPrivateSubnet1ID
        - !ImportValue RDSSeekerPrivateSubnet2ID
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-aurora-postgres-subnet-group

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DatabaseName: !Ref DBName
      Engine: aurora-postgresql
      EngineVersion: "13.16"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      StorageEncrypted: true
      DBClusterParameterGroupName: !Ref AuroraDBClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue SeekerDBSecurityGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 02:00-03:00
      PreferredMaintenanceWindow: Sun:03:00-Sun:04:00
      Tags:
        - Key: Name
          Value: aurora-postgres-cluster

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: aurora-postgres-instance
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-postgresql
      DBInstanceClass: !Ref InstanceClass
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub ${NamePrefix}-aurora-postgres-instance

Outputs:
  DBClusterIdentifier:
    Description: Identifier of the Aurora PostgreSQL cluster
    Value: !Ref DBClusterIdentifier

