AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an Ubuntu Service on AWS Fargate without ALB.

Resources:
  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue ECSClusterNameSeeker
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 1
      LaunchType: FARGATE
      HealthCheckGracePeriodSeconds: 60
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: 
            - !ImportValue ECSseekerSecurityGroupID
          Subnets:
            - !ImportValue ECSSeekerPrivateSubnet1ID
            - !ImportValue ECSSeekerPrivateSubnet2ID

      PlatformVersion: 1.4.0
      TaskDefinition: !ImportValue UbuntuTaskDefinitionArn
      PropagateTags: SERVICE
      Tags:
        - Key: Name
          Value: ubuntu-service

Outputs:
  ECSServiceName:
    Description: 'Nombre del servicio ECS desplegado'
    Value: !Ref ECSService 
