AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Definition for Ubuntu Linux (ARM) on ECS Fargate in Oregon'

Parameters:
  Imagencontainer:
    Default: '258840583819.dkr.ecr.us-west-2.amazonaws.com/seeker:1.23'
    Type: String
    Description: Used to resolved images of container.    

Resources:
  # IAM Role for ECS Task Execution
  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ECSFargateTaskExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'

  # ECS Task Definition
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'UbuntuTask'
      Cpu: '4096' # 4 vCPU (para ARM)
      Memory: '16384' # 16 GB
      EphemeralStorage:
        SizeInGiB: 40 # Almacenamiento efímero
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: ARM64 # Arquitectura ARM
      ContainerDefinitions:
        - Name: ubuntu
          Image: !Ref Imagencontainer # Imagen pública de Ubuntu desde Docker Hub
          Essential: true
          PortMappings:
            - ContainerPort: 9000
              HostPort: 9000
              Protocol: tcp
              Name: ubuntuhttp-port
              AppProtocol: http
          Command:
            - sleep
            - "3600" # activo por 1 hora
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: '/ecs/ubuntu'
              awslogs-stream-prefix: 'ubuntu'
              awslogs-region: !Ref 'AWS::Region'

Outputs:
  TaskDefinitionArn:
    Description: 'ARN de la definición de tarea de ECS'
    Value: !Ref ECSTaskDefinition
    Export:
      Name: UbuntuTaskDefinitionArn
