AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Definition for Ubuntu Linux (ARM) on ECS Fargate in Oregon'

Parameters:
  Imagencontainer:
    Default: '258840583819.dkr.ecr.us-west-2.amazonaws.com/seeker:1.23'
    Type: String
    Description: Used to resolved images of container.    

Resources:
  # IAM Role for ECS Task Execution
  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ECSFargateTaskExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'

  # ECS Task Definition
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'UbuntuTask'
      Cpu: '4096' # 4 vCPU (para ARM)
      Memory: '16384' # 16 GB
      EphemeralStorage:
        SizeInGiB: 40 # Almacenamiento efímero
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: ARM64 # Arquitectura ARM
      ContainerDefinitions:
        - Name: ubuntu
          Image: !Ref Imagencontainer # Imagen pública de Ubuntu desde Docker Hub
          Essential: true
          PortMappings:
            - ContainerPort: 9000
              HostPort: 9000
              Protocol: tcp
              Name: ubuntuhttp-port
              AppProtocol: http
          Command:
            - sleep
            - "3600" # activo por 1 hora
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: '/ecs/ubuntu'
              awslogs-stream-prefix: 'ubuntu'
              awslogs-region: !Ref 'AWS::Region'

Outputs:
  TaskDefinitionArn:
    Description: 'ARN de la definición de tarea de ECS'
    Value: !Ref ECSTaskDefinition
    Export:
      Name: UbuntuTaskDefinitionArn


----------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Definition for Ubuntu Linux (ARM) on ECS Fargate with seeker initialization.'

Parameters:
  Imagencontainer:
    Default: '258840583819.dkr.ecr.us-west-2.amazonaws.com/seeker:1.23'
    Type: String
    Description: Used to resolve images of container.    

Resources:
  # IAM Role for ECS Task Execution
  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ECSFargateTaskExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'

  # ECS Task Definition
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'UbuntuTask'
      Cpu: '4096'
      Memory: '16384'
      EphemeralStorage:
        SizeInGiB: 40
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: ARM64
      ContainerDefinitions:
        - Name: ubuntu
          Image: !Ref Imagencontainer
          Essential: true
          Command:
            - /bin/sh
            - "-c"
            - |
              set -e
              echo "Starting seeker setup..."
              sh ./seeker-server-linux64-2025.1.0.sh accept-license=agree install-dir=/home/seeker server-http-port=8080 server-https-port=8443
              /home/seeker/install/sk_ctl start
              tail -f /dev/null
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
            - ContainerPort: 8443
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: '/ecs/ubuntu'
              awslogs-stream-prefix: 'ubuntu'
              awslogs-region: !Ref 'AWS::Region'

Outputs:
  TaskDefinitionArn:
    Description: 'ARN de la definición de tarea de ECS'
    Value: !Ref ECSTaskDefinition
    Export:
      Name: UbuntuTaskDefinitionArn


---------------------------------------------------------------------------------------------------
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Definition for Ubuntu Linux (ARM) on ECS Fargate with seeker initialization.'

Parameters:
  Imagencontainer:
    Default: '258840583819.dkr.ecr.us-west-2.amazonaws.com/seeker:3.1'
    Type: String
    Description: Used to resolve images of container.    

Resources:
  # IAM Role for ECS Task Execution
  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ECSFargateTaskExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'

  # ECS Task Definition
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'UbuntuTask'
      Cpu: '4096'
      Memory: '16384'
      EphemeralStorage:
        SizeInGiB: 40
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      ContainerDefinitions:
        - Name: ubuntu
          Image: !Ref Imagencontainer
          Essential: true
          Command:
            - /bin/bash
            - "-c"
            - |
              set -e
              echo "Starting seeker setup..."
              sh ./seekerdeploy/seeker-server-linux64-2025.1.0.sh accept-license=agree install-dir=/home/seeker server-http-port=8080 server-https-port=8443
              /seekerdeploy/install/sk_ctl start
              tail -f /dev/null
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
            - ContainerPort: 8443
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: '/ecs/logs-seeker'
              awslogs-stream-prefix: 'logs-seeker'
              awslogs-region: !Ref 'AWS::Region'

Outputs:
  TaskDefinitionArn:
    Description: 'ARN de la definición de tarea de ECS'
    Value: !Ref ECSTaskDefinition
    Export:
      Name: UbuntuTaskDefinitionArn
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

Resources:
  # ECS Task Definition
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'UbuntuTask'
      Cpu: '4096'
      Memory: '16384'
      Volumes:
        - Name: seekerEFS
          EfsVolumeConfiguration:
            FileSystemId: !ImportValue SeekerEFSFileSystemId
            AuthorizationConfig:
              AccessPointId: !ImportValue SeekerEFSAccessPointId
              Iam: "ENABLED"
            RootDirectory: "/seeker"
            TransitEncryption: "ENABLED"

      ContainerDefinitions:
        - Name: ubuntu
          Image: !Ref Imagencontainer
          MountPoints:
            - SourceVolume: seekerEFS
              ContainerPath: /seeker
---------------------------------------------------------------------------------------------------------------------
Resources:
  # ECS Task Definition
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'UbuntuTask'
      Cpu: '4096'
      Memory: '16384'
      EphemeralStorage:
        SizeInGiB: 40
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      Volumes:
        - Name: seekerEFS
          EfsVolumeConfiguration:
            FileSystemId: "fs-XXXXXXXX"  # Cambia esto por el ID del sistema de archivos EFS
            AuthorizationConfig:
              AccessPointId: "fsap-XXXXXXXX"  # Cambia esto por el ID del Access Point de EFS
              Iam: "ENABLED"
            RootDirectory: "/seeker"
            TransitEncryption: "ENABLED"

      ContainerDefinitions:
        - Name: ubuntu
          Image: !Ref Imagencontainer
          Essential: true
          Command:
            - /bin/bash
            - "-c"
            - |
              set -e
              echo "Starting seeker setup..."
              sh ./seekerdeploy/seeker-server-linux64-2025.1.0.sh accept-license=agree install-dir=/home/seeker server-http-port=8080 server-https-port=8443
              /seekerdeploy/install/sk_ctl start
              tail -f /dev/null
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
            - ContainerPort: 8443
              Protocol: tcp
          MountPoints:
            - SourceVolume: seekerEFS
              ContainerPath: /seeker  # Monta el volumen en /seeker dentro del contenedor

          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: '/ecs/logs-seeker'
              awslogs-stream-prefix: 'logs-seeker'
              awslogs-region: !Ref 'AWS::Region'




      
