AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WAF asociado a un ALB existente en Oregón (us-west-2)'

Parameters:
  ALBArn:
    Type: String
    Description: 'ARN del Application Load Balancer (ALB) existente en Oregón'

Resources:
  # 📌 Web ACL de AWS WAF
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: "WAF-Oregon-ALB"
      Scope: REGIONAL
      DefaultAction:
        Allow: {}  # Permitir tráfico por defecto (puedes cambiarlo a Block)
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: "WAF-Oregon-Metrics"
      Rules:
        - Name: "AWS-Managed-CommonRules"
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "CommonRules"

        - Name: "AWS-Managed-KnownBadInputs"
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "KnownBadInputs"

        - Name: "RateLimitRule"
          Priority: 3
          Statement:
            RateBasedStatement:
              Limit: 2000  # Límite de 2000 solicitudes en 5 minutos
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "RateLimitRule"

  # 📌 Asociar el WAF al ALB
  WAFWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ALBArn
      WebACLArn: !GetAtt WAFWebACL.Arn

Outputs:
  WAFWebACLArn:
    Description: "ARN del Web ACL de AWS WAF"
    Value: !GetAtt WAFWebACL.Arn
