AWSTemplateFormatVersion: '2010-09-09'
Description: Esta plantilla crea rol LucidChart
Parameters:
  AccountIdLucichart:
    Type: String
    Description: Lucichart AWS Account ID
    Default: '799803075172'
  ExternalIdLucichart:
    Type: String
    Description: >-
      The primary function of the External ID is to address and prevent the
      'confused deputy' problem
    Default: b6569f46-0641-4eb1-b50a-a56122160f0a
Resources:
  LucichartCustomPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: Lucichart
      Description: Lucichart Custom Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'apigateway:GET'
              - 'autoscaling:DescribeAutoScalingGroups'
              - 'autoscaling:DescribeLaunchConfigurations'
              - 'cloudfront:ListDistributions'
              - 'cloudfront:ListTagsForResource'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:ListTables'
              - 'dynamodb:ListTagsOfResource'
              - 'ec2:DescribeCustomerGateways'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInternetGateways'
              - 'ec2:DescribeNatGateways'
              - 'ec2:DescribeNetworkAcls'
              - 'ec2:DescribeNetworkInterfaces'
              - 'ec2:DescribeRouteTables'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeTransitGateways'
              - 'ec2:DescribeTransitGatewayAttachments'
              - 'ec2:DescribeTransitGatewayRouteTables'
              - 'ec2:DescribeVolumes'
              - 'ec2:DescribeVpcs'
              - 'ec2:DescribeVpcEndpoints'
              - 'ec2:DescribeVpcEndpointConnections'
              - 'ec2:DescribeVpnConnections'
              - 'ec2:DescribeVpnGateways'
              - 'ec2:DescribeVpcPeeringConnections'
              - 'ec2:SearchTransitGatewayRoutes'
              - 'ecs:DescribeClusters'
              - 'ecs:DescribeServices'
              - 'ecs:DescribeTasks'
              - 'ecs:ListClusters'
              - 'ecs:ListServices'
              - 'ecs:ListTasks'
              - 'eks:DescribeCluster'
              - 'eks:ListClusters'
              - 'elasticfilesystem:DescribeFileSystems'
              - 'elasticache:DescribeCacheClusters'
              - 'elasticache:DescribeCacheSubnetGroups'
              - 'elasticloadbalancing:DescribeLoadBalancers'
              - 'elasticloadbalancing:DescribeTags'
              - 'elasticloadbalancing:DescribeTargetGroups'
              - 'elasticloadbalancing:DescribeTargetHealth'
              - 'es:DescribeElasticsearchDomains'
              - 'es:ListDomainNames'
              - 'es:ListTags'
              - 'iam:ListAccountAliases'
              - 'kinesis:DescribeStream'
              - 'kinesis:ListShards'
              - 'kinesis:ListStreams'
              - 'kinesis:ListTagsForStream'
              - 'lambda:ListFunctions'
              - 'lambda:ListTags'
              - 'redshift:DescribeClusters'
              - 'rds:DescribeDBClusters'
              - 'rds:DescribeDBInstances'
              - 'rds:ListTagsForResource'
              - 'route53:ListHostedZones'
              - 'route53:ListResourceRecordSets'
              - 'route53:ListTagsForResource'
              - 's3:GetBucketLocation'
              - 's3:GetBucketNotification'
              - 's3:GetBucketPolicyStatus'
              - 's3:GetBucketTagging'
              - 's3:GetEncryptionConfiguration'
              - 's3:ListAllMyBuckets'
              - 'sns:GetTopicAttributes'
              - 'sns:ListTopics'
              - 'sns:ListTagsForResource'
              - 'sqs:GetQueueAttributes'
              - 'sqs:ListQueues'
              - 'sqs:ListQueueTags'
              - 'states:DescribeActivity'
              - 'states:ListActivities'
              - 'states:DescribeStateMachine'
              - 'states:ListStateMachines'
              - 'states:ListTagsForResource'
              - 'sts:GetCallerIdentity'
            Resource:
              - '*'
  LucichartRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: Lucichart
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AccountIdLucichart
                    - ':root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId':
                  Ref: ExternalIdLucichart
      ManagedPolicyArns:
        - Ref: LucichartCustomPolicy
Outputs:
  Version:
    Value: '1.23'
  LucichartRoleArn:
    Value:
      'Fn::GetAtt':
        - LucichartRole
        - Arn
