version: 2.1

#parameters:
#  pipeline_config:
#    type: string
#    default: config_cuenta1.yml

executors:
  arm-executor:
    environment:
      AWS_PAGER: ""
      ENTERPRISE_NAME: nuevo
      GROUP_NAME: ipic
      SERVICE_NAME: ecs
    machine:
      image: ubuntu-2004:current
#    resource_class: arm.medium
    resource_class: arm.medium

jobs:
  deploy:
    executor: arm-executor
    environment:
      CIRCLE_PIPELINE_NUM: << pipeline.number >>
      DEPLOY_ENV: <<parameters.DEPLOY_ENV>>
      RESOURCE_NAME: <<parameters.RESOURCE_NAME>>
    parameters:
      DEPLOY_ENV:
        type: string
        enum: [dev]
      TEMPLATE_FILE_NAME:
        type: string
      RESOURCE_NAME:
        type: string
    steps:
      - checkout
      - run:
          name: Install AWS cli ☁️ 📦
          command: |
            chmod +x ./scripts/install_aws.sh
            ./scripts/install_aws.sh <<parameters.DEPLOY_ENV>> <<pipeline.number>>
      - run: chmod +x ./scripts/*
      - run:
          name: Debug params
          command: |
            echo "jobs_file=<< pipeline.parameters.jobs_file >>"
            echo "workflow_files_csv=<< pipeline.parameters.workflow_files_csv >>"
      - run:
          name: Deploying <<parameters.RESOURCE_NAME>> 🎯
          command: ./scripts/deploy.sh <<parameters.TEMPLATE_FILE_NAME>> <<parameters.RESOURCE_NAME>>
          no_output_timeout: 40m